### ISSUE TITLE
Show the actual commit version at the bottom of the site

### ISSUE THREAD

**Issue by lunky** [WpgDotNetUG/WebsiteV2_Elm#12]
The commit of the deployed version should be shown at the footer of the site

**Comment by mikesigs** [comment]
I'll take this one. Thanks for the suggestion @amirci.

**Comment by mikesigs** [comment]
So what's the thinking here. We want to show the git version hash in the footer? Instead of the `aabbcc` that's there right now? What about the `v0.1` number? This would probably be gotten from a tag in git (which there are none currently).

I couldn't see any obvious way to do this with Elm itself. Does anyone know if it's possible? In ASP.NET we could use a technique like [this](https://stackoverflow.com/questions/6118187/how-to-display-version-number-on-the-footer-of-an-mvc3-app). But I'm not sure there is an equivalent in Elm.

I decided maybe using gulp was the way to go. Getting the hash from git in gulp was the easy part. Now I am trying to use gulp-inject-string to get the value into the index.html file, but kinda stuck.

So I'm wondering, am I off track here? Can I do this easily with Elm somehow?

**Comment by amirci** [comment]
I think we could use a _port_ to store the hash so Elm can display it on the view.

**Comment by amirci** [comment]
Fixed with PR #27
